name: npm test

on: push

jobs:
 test:
  name: test npm
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node: ['16'] # miniflare only runs on node >= 16.7.0

  steps:
   # Checkout code
   - uses: actions/checkout@v2

   # Need to do the javascript builds for the wrangler to have compiled
   # typescript to work with.
   - uses: actions/setup-node@v2
     with:
       node-version: ${{ matrix.node }}

   # Install node dependencies
   - run: npm ci

   # Execute test script that runs miniflare in the background
   # as a local cloudflare api simulator target.
   - run: npm test
